Task1
danchikov-a/phoneshop-servlet-api pull request #3
Opened 2022-01-24 11:33 UTC by danchikov-a

Implement ArrayListProductDao
Implement ArrayListProductDaoTest 
Use the DAO in the ProductListPageServlet
Implement ProductListPageServletTest using junit4 and mockito

2022-01-26 11:20 UTC, devjohnsmith1 requested changes

2022-01-26 11:20 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +    private long maxId = 1L;
для чего нужен maxId? Почему не подходит добавление элемента в конец списка?

2022-01-26 11:20 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +        saveSampleProducts();
Можем ли мы вынести этот метод из конструктора?

2022-01-26 11:20 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                    .filter(product -> id.equals(product.getId()))
что если мы передаём пустой id?

2022-01-26 11:20 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/ArrayListProductDao.java
> +                product.setId(maxId++);
Должен ли Id продукта зависеть от его позиции в списке?

2022-01-26 11:20 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/Product.java
> +    }
В конструкторе слишком много параметров (> 5). Подумай (+ почитай), какие есть способы избежать этого

2022-01-26 11:20 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/Product.java
>      public Product(Long id, String code, String description, BigDecimal price, Currency currency, int stock, String imageUrl) {
Слишком большой конструктор

2022-01-26 11:20 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
>          request.getRequestDispatcher("/WEB-INF/pages/productList.jsp").forward(request, response);
выноси hardcode строки в константы

2022-01-26 11:20 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +import static org.junit.Assert.*;
нужны ли тебе все элементы из этой библиотеки?

2022-01-26 11:20 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
>      public void testFindProductsNoResults() {
названия тестовых методов - посмотри на конвенции should....when....then

2022-01-26 11:20 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        Product product = new Product("test-code", "Samsung Galaxy S", new BigDecimal(100), usd, 100, "https://raw.githubusercontent.com/andrewosipenko/phoneshop-ext-images/master/manufacturer/Samsun
выноси константы

2022-01-26 11:20 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +        productDao.save(product);
почему тестируешь на реальных сущностях?

2022-01-26 11:20 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/web/ProductListPageServletTest.java
> +import static org.mockito.ArgumentMatchers.*;
лишние импорты

2022-01-27 16:01 UTC, devjohnsmith1 requested changes

2022-01-27 16:10 UTC, devjohnsmith1 commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    }
используй junit4 + mockito

2022-01-27 16:20 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/model/product/Product.java
>      public Product(Long id, String code, String description, BigDecimal price, Currency currency, int stock, String imageUrl) {
окей, тогда оставляй

2022-01-27 16:30 UTC, danchikov-a commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    }
в junit expected не пойдет для теста? и каким образом mockito применить?

2022-01-27 20:21 UTC, danchikov-a commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    }
и как мне  правильно использовать dao в качестве мока? у меня же при создании dao инициализируется первоначальный список с продуктами. А при создании мока не получается проинициализировать? что почитать по этой теме, а то я погуглил и не нашел решения

2022-01-27 21:26 UTC, danchikov-a commented on src/test/java/com/es/phoneshop/model/product/ArrayListProductDaoTest.java
> +    }
какие варианты есть, чтобы протестить dao с помощью mockito?

2022-01-28 14:55 UTC, devjohnsmith1 approved these changes

2022-01-28 15:05 UTC, merged