Task3
danchikov-a/phoneshop-servlet-api pull request #5
Opened 2022-02-08 17:04 UTC by danchikov-a

Implement HttpSessionCartService
Implement product adding to cart from PDP
Implement selfcheck task showing 3 recent product in the bottom of the site

2022-02-09 11:01 UTC, devjohnsmith1 requested changes

2022-02-09 16:17 UTC, danchikov-a commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
каким образом я могу переименовать переопределенный метод?

2022-02-10 09:17 UTC, devjohnsmith1 commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
> каким образом я могу переименовать переопределенный метод?

Верно

2022-02-11 07:38 UTC, devjohnsmith1 approved these changes

2022-02-11 07:42 UTC, devjohnsmith1 requested changes
Фигурные скобки и название проперти файла

2022-02-11 08:05 UTC, devjohnsmith1 approved these changes

2022-02-11 08:13 UTC, merged